const TRACK_MOUSE_POSITION = "mouse/tracking/duck/TRACK_MOUSE_POSITION";
const CLEAR_MOUSE_POSITION = "mouse/tracking/duck/CLEAR_MOUSE_POSITION";

export default {
	TRACK_MOUSE_POSITION,
	CLEAR_MOUSE_POSITION
};