const CREATE_DRAGGABLE = "mouse/dragAndDrop/duck/CREATE_DRAGGABLE";
const CREATE_DROP_ZONE = "mouse/dragAndDrop/duck/CREATE_DROP_ZONE";
const SELECT_DRAGGABLE = "mouse/dragAndDrop/duck/SELECT_DRAGGABLE";
const SELECT_DROP_ZONE = "mouse/dragAndDrop/duck/SELECT_DROP_ZONE";
const DROP_SUCCESSFUL = "mouse/dragAndDrop/duck/DROP_SUCCESSFUL";
const SET_DROP_ZONE_BOUNDS = "mouse/dragAndDrop/duck/SET_DROP_ZONE_BOUNDS";

export default {
	CREATE_DRAGGABLE,
	CREATE_DROP_ZONE,
	SELECT_DRAGGABLE,
	SELECT_DROP_ZONE,
	DROP_SUCCESSFUL,
	SET_DROP_ZONE_BOUNDS
};