const GET_SCROLL_POSITION = "events/scroll/duck/GET_SCROLL_POSITION";
const LOCK_SCROLL_POSITION = "events/scroll/duck/LOCK_SCROLL_POSITION";
const UNLOCK_SCROLL_POSITION = "events/scroll/duck/UNLOCK_SCROLL_POSITION";

export default {
	GET_SCROLL_POSITION,
	LOCK_SCROLL_POSITION,
	UNLOCK_SCROLL_POSITION
};