const ADD_DROP_ZONE_TO_ARRAY = "game/interactables/ADD_DROP_ZONE_TO_ARRAY";
const CHANGE_DROP_ZONE_STATUS = "game/interactables/CHANGE_DROP_ZONE_STATUS";
const SELECT_DROP_ZONE = "game/interactables/SELECT_DROP_ZONE";
const DROP_ITEM_IN_DROP_ZONE = "game/interactables/DROP_ITEM_IN_DROP_ZONE";
const ADD_EVENT_ZONE_TO_ARRAY = "game/interactables/ADD_EVENT_ZONE_TO_ARRAY";
const CHANGE_EVENT_ZONE_STATUS = "game/interactables/CHANGE_EVENT_ZONE_STATUS";

export default {
	ADD_DROP_ZONE_TO_ARRAY,
	CHANGE_DROP_ZONE_STATUS,
	SELECT_DROP_ZONE,
	DROP_ITEM_IN_DROP_ZONE,
	ADD_EVENT_ZONE_TO_ARRAY,
	CHANGE_EVENT_ZONE_STATUS
};