const CREATE_NEW_ITEM = "game/inventory/duck/CREATE_NEW_ITEM";
const ADD_ITEM_TO_INVENTORY = "game/inventory/duck/ADD_ITEM_TO_INVENTORY";
const UPDATE_ITEM_IN_INVENTORY = "game/inventory/duck/UPDATE_ITEM_IN_INVENTORY";
const REMOVE_ITEM_FROM_INVENTORY = "game/inventory/duck/REMOVE_ITEM_FROM_INVENTORY";
const CLEAR_INVENTORY = "game/inventory/duck/CLEAR_INVENTORY";
const PLACE_ITEM_IN_DOM = "game/inventory/duck/PLACE_ITEM_IN_DOM";

export default {
	CREATE_NEW_ITEM,
	ADD_ITEM_TO_INVENTORY,
	UPDATE_ITEM_IN_INVENTORY,
	REMOVE_ITEM_FROM_INVENTORY,
	CLEAR_INVENTORY,
	PLACE_ITEM_IN_DOM
};